name: ClansPE
author: Zeao
description: The Official ClansPE plugin, originally FactionsPro.
version: 2.0.0
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA7]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
